# -*- coding: utf-8 -*-
"""AI_DETECTOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dh9gYpo8YDw-3-9sCHZt1xLYs9famdOQ
"""

!pip install scikit-learn pandas numpy joblib
!pip install pdfplumber pytesseract pillow

import pandas as pd
import joblib
import pdfplumber
import pytesseract

from PIL import Image
from google.colab import files

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv("dataset.csv")

print("Dataset Loaded Successfully!")

X = df["text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = Pipeline([

    ("vectorizer", TfidfVectorizer()),

    ("classifier", LogisticRegression())

])

model.fit(X_train, y_train)

print("\nModel Trained Successfully!")

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print(f"\nAccuracy: {accuracy * 100:.2f}%")

joblib.dump(model, "ai_detector.pkl")

def detect_ai(text):

    prediction = model.predict([text])[0]

    probability = model.predict_proba([text])[0]

    human_score = probability[0] * 100
    ai_score = probability[1] * 100

    print("\n========== RESULT ==========")

    if prediction == 1:
        print("Prediction : AI Generated 🤖")
    else:
        print("Prediction : Human Written 👨")

    print(f"AI Confidence    : {ai_score:.2f}%")
    print(f"Human Confidence : {human_score:.2f}%")

    print("============================")

while True:

    print("\n===================================")
    print("        AI DETECTOR 🤖")
    print("===================================")

    print("\n1. Enter Text")
    print("2. Upload PDF")
    print("3. Upload Image")
    print("4. Exit")

    choice = input("\nEnter your choice: ")

    if choice == "1":

        text = input("\nEnter text: ")

        detect_ai(text)

    elif choice == "2":

        print("\nUpload PDF File")

        uploaded = files.upload()

        for filename in uploaded.keys():

            text = ""

            with pdfplumber.open(filename) as pdf:

                for page in pdf.pages:

                    extracted = page.extract_text()

                    if extracted:
                        text += extracted

            print("\nExtracted Text:\n")
            print(text[:1000])

            detect_ai(text)

    elif choice == "3":

        print("\nUpload Image File")

        uploaded = files.upload()

        for filename in uploaded.keys():

            image = Image.open(filename)

            extracted_text = pytesseract.image_to_string(image)

            print("\nExtracted Text:\n")
            print(extracted_text[:1000])

            detect_ai(extracted_text)

    elif choice == "4":

        print("\nProgram Closed.")
        break

    else:

        print("\nInvalid Choice!")